コンパイル時にlodashでエラーが出るのを修正
まだ完璧じゃない：
[0] src/top.page.ts(65,10): error TS2339: Property '_' does not exist on type 'TopPage'.